### ISSUE TITLE
`decrypt ∘ encrypt = id` but `encrypt ∘ decrypt ≠ id`

### ISSUE THREAD

**Issue by aiya000** [hmoog/crypto-ts#10]
Hi.
I wrote a code:

```typescript
import { AES, enc } from 'crypto-ts'

const essence: Readonly<Array<string>> = ['cccc', 'bbb']

export function encrypt(plain: string): string {
  let result = plain
  let i = 0

  for (const key of essence) {
    console.log(`${i++}th: ${result}`)
    result = AES.encrypt(result, key).toString()
  }
  console.log(`${i++}th: ${result}`)

  return result
}

export function decrypt(encrypted: string): string {
  const reversed = essence.slice().reverse()

  let result = encrypted
  let i = 0

  for (const key of reversed) {
    console.log(`${i++}th: ${result}`)
    result = AES.decrypt(result, key).toString(enc.Utf8)
  }
  console.log(`${i++}th: ${result}`)

  return result
}
```

and wrote 2 tests

`decrypt ∘ encrypt = id`?
```typescript
  import { equal } from 'assert'
  import { encrypt, decrypt } from './password'

  equal(
    decrypt(encrypt('aaa')),
    'aaa',
  )
```

This is succeed. But...

`encrypt ∘ decrypt = id`?

```typescript
  import { equal } from 'assert'
  import { encrypt, decrypt } from './password'

  const encrypted = encrypt('aaa')

  equal(
    encrypt(decrypt(encrypted)),
    encrypted,
  )
```

This is not succeed.

This outputs:

```
      at Object.encrypt (src/data/password.ts:21:13)
      0th: aaa
      1th: U2FsdGVkX1+dqc1ONOoJe0Emtg7hk3gaw2dFDDpz7i0=
      2th: U2FsdGVkX1+T4l2tnqC6DkJhJ267S44fePf2aurDJQ1dnRL2N8gdOgR+e89nafrs2CJABiPL2r8kSL0HfWks3A==

      at Object.decrypt (src/data/password.ts:50:13)
      0th: U2FsdGVkX1+T4l2tnqC6DkJhJ267S44fePf2aurDJQ1dnRL2N8gdOgR+e89nafrs2CJABiPL2r8kSL0HfWks3A==
      1th: U2FsdGVkX1+dqc1ONOoJe0Emtg7hk3gaw2dFDDpz7i0=
      2th: aaa

      at Object.encrypt (src/data/password.ts:21:13)
      0th: aaa
      1th: U2FsdGVkX19f6NW8lX7mibHUo2ehVBb+iOC2G1rDFO0=
      2th: U2FsdGVkX19rZGGnvKyakv0FHJGx9FgyXivUHkD1xVuPNG8yyiYi8jh3JF372n6diJ/xekV2L7BA2NN4zgn0qA==
```

This is so strange, because `encrypt()` returns different value for the same input.

Some ideas? please x(

**Comment by aiya000** [comment]
FYI, the 2nd test (`encrypt ∘ decrypt = id`?) result is
```
    Expected value to be equal to:
      "U2FsdGVkX1+T4l2tnqC6DkJhJ267S44fePf2aurDJQ1dnRL2N8gdOgR+e89nafrs2CJABiPL2r8kSL0HfWks3A=="
    Received:
      "U2FsdGVkX19rZGGnvKyakv0FHJGx9FgyXivUHkD1xVuPNG8yyiYi8jh3JF372n6diJ/xekV2L7BA2NN4zgn0qA=="
```

**Comment by unhappychoice** [comment]
I think this is the reason https://github.com/brix/crypto-js/issues/119#issuecomment-350373031
It's not `crypto-ts` project but `crypto-js` though but the implementations seems to be same

**Comment by aiya000** [comment]
Indeed!
I see... Thanks!
